name: Hello World Workflow

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v2 
      - name: Hello World Step
        run: echo "Hello World!"
        shell: bash
  goodbye_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Goodbye World Step
        run: echo "Goodbye World!"
        shell: bash
```
