name: Hello World Workflow

on: 
  workflow_dispatch:
  push:
    branches: 
      - testing

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Hello World Step
        run: echo "Hello World!"
        shell: bash

 